# coding: utf-8

"""
    EPIC API

    REST API for interacting with EPIC (https://epic.zenotech.com) services. <br />                             Used by the EPIC CLI (https://github.com/zenotech/epic-cli).                             Please note this API is in BETA and does not yet contain                             all EPIC functionality.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@zenotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import epiccore
from epiccore.model.limit import Limit
globals()['Limit'] = Limit
from epiccore.model.limits import Limits


class TestLimits(unittest.TestCase):
    """Limits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimits(self):
        """Test Limits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Limits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
