# coding: utf-8

"""
    EPIC API

    REST API for interacting with EPIC (https://epic.zenotech.com) services. <br />                             Used by the EPIC CLI (https://github.com/zenotech/epic-cli).                             Please note this API is in BETA and does not yet contain                             all EPIC functionality.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@zenotech.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import epiccore
from epiccore.api.jobauth_api import JobauthApi  # noqa: E501
from epiccore.rest import ApiException


class TestJobauthApi(unittest.TestCase):
    """JobauthApi unit test stubs"""

    def setUp(self):
        self.api = epiccore.api.jobauth_api.JobauthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jobauth_list(self):
        """Test case for jobauth_list

        """
        pass

    def test_jobauth_read(self):
        """Test case for jobauth_read

        """
        pass

    def test_jobauth_update(self):
        """Test case for jobauth_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
