# coding: utf-8

"""
    EPIC API

    REST API for interacting with EPIC (https://epic.zenotech.com) services. <br />                             Please note this API is in BETA and does not yet contain                             all EPIC functionality.

    The version of the OpenAPI document: v2
    Contact: support@zenotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from epiccore.models.task_quote import TaskQuote
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class JobQuote(BaseModel):
    """
    JobQuote
    """ # noqa: E501
    task_quotes: Optional[List[TaskQuote]] = Field(default=None, description="List of job quotes for individual tasks in this request")
    totals: Optional[List[TaskQuote]] = Field(default=None, description="List of job quote totals for this request")
    __properties: ClassVar[List[str]] = ["task_quotes", "totals"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobQuote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in task_quotes (list)
        _items = []
        if self.task_quotes:
            for _item in self.task_quotes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['task_quotes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in totals (list)
        _items = []
        if self.totals:
            for _item in self.totals:
                if _item:
                    _items.append(_item.to_dict())
            _dict['totals'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of JobQuote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_quotes": [TaskQuote.from_dict(_item) for _item in obj.get("task_quotes")] if obj.get("task_quotes") is not None else None,
            "totals": [TaskQuote.from_dict(_item) for _item in obj.get("totals")] if obj.get("totals") is not None else None
        })
        return _obj


