# coding: utf-8

"""
    EPIC API

    REST API for interacting with EPIC (https://epic.zenotech.com) services. <br />                             Used by the EPIC CLI (https://github.com/zenotech/epic-cli).                             Please note this API is in BETA and does not yet contain                             all EPIC functionality.  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@zenotech.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import epiccore
from epiccore.api.jobstep_api import JobstepApi  # noqa: E501
from epiccore.rest import ApiException


class TestJobstepApi(unittest.TestCase):
    """JobstepApi unit test stubs"""

    def setUp(self):
        self.api = epiccore.api.jobstep_api.JobstepApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jobstep_cancel(self):
        """Test case for jobstep_cancel

        """
        pass

    def test_jobstep_list(self):
        """Test case for jobstep_list

        """
        pass

    def test_jobstep_logs_read(self):
        """Test case for jobstep_logs_read

        """
        pass

    def test_jobstep_logs_update(self):
        """Test case for jobstep_logs_update

        """
        pass

    def test_jobstep_read(self):
        """Test case for jobstep_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
